all:
  children:
    dc_servers:
      hosts:
        dc:
          ansible_host: 172.16.0.1
    app_servers:
      hosts:
        srv:
          ansible_host: 172.16.0.10
    firewall_servers:
      hosts:
        fw:
          ansible_host: 172.16.0.254
    workstations:
      hosts:
        workstation:
          ansible_host: 172.16.0.100

    # Group semua Windows hosts
    windows:
      children:
        dc_servers:
        app_servers:
        firewall_servers:
        workstations:
